CREATE TABLE `ps_map_data_halflife_cstrike` (
  `dataid` int unsigned NOT NULL default '0',
  `ctkills` smallint unsigned NOT NULL default '0',
  `terroristkills` smallint unsigned NOT NULL default '0',
  `joinedct` smallint unsigned NOT NULL default '0',
  `joinedterrorist` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `bombdefuseattempts` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `bombexploded` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombrunner` smallint unsigned NOT NULL default '0',
  `killedhostages` smallint unsigned NOT NULL default '0',
  `rescuedhostages` smallint unsigned NOT NULL default '0',
  `touchedhostages` smallint unsigned NOT NULL default '0',
  `vipescaped` smallint unsigned NOT NULL default '0',
  `vipkilled` smallint unsigned NOT NULL default '0',
  `ctwon` smallint unsigned NOT NULL default '0',
  `ctlost` smallint unsigned NOT NULL default '0',
  `terroristwon` smallint unsigned NOT NULL default '0',
  `terroristlost` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_data_halflife_cstrike` (
  `dataid` int unsigned NOT NULL default '0',
  `ctkills` smallint unsigned NOT NULL default '0',
  `terroristkills` smallint unsigned NOT NULL default '0',
  `ctdeaths` smallint unsigned NOT NULL default '0',
  `terroristdeaths` smallint unsigned NOT NULL default '0',
  `joinedct` smallint unsigned NOT NULL default '0',
  `joinedterrorist` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `bombdefuseattempts` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `bombexploded` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombspawned` smallint unsigned NOT NULL default '0',
  `bombrunner` smallint unsigned NOT NULL default '0',
  `killedhostages` smallint unsigned NOT NULL default '0',
  `rescuedhostages` smallint unsigned NOT NULL default '0',
  `touchedhostages` smallint unsigned NOT NULL default '0',
  `vip` smallint unsigned NOT NULL default '0',
  `vipescaped` smallint unsigned NOT NULL default '0',
  `vipkilled` smallint unsigned NOT NULL default '0',
  `ctwon` smallint unsigned NOT NULL default '0',
  `ctlost` smallint unsigned NOT NULL default '0',
  `terroristwon` smallint unsigned NOT NULL default '0',
  `terroristlost` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_maps_halflife_cstrike` (
  `dataid` int unsigned NOT NULL default '0',
  `ctkills` smallint unsigned NOT NULL default '0',
  `terroristkills` smallint unsigned NOT NULL default '0',
  `ctdeaths` smallint unsigned NOT NULL default '0',
  `terroristdeaths` smallint unsigned NOT NULL default '0',
  `joinedct` smallint unsigned NOT NULL default '0',
  `joinedterrorist` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `bombdefuseattempts` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `bombexploded` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombspawned` smallint unsigned NOT NULL default '0',
  `bombrunner` smallint unsigned NOT NULL default '0',
  `killedhostages` smallint unsigned NOT NULL default '0',
  `rescuedhostages` smallint unsigned NOT NULL default '0',
  `touchedhostages` smallint unsigned NOT NULL default '0',
  `vip` smallint unsigned NOT NULL default '0',
  `vipescaped` smallint unsigned NOT NULL default '0',
  `vipkilled` smallint unsigned NOT NULL default '0',
  `ctwon` smallint unsigned NOT NULL default '0',
  `ctlost` smallint unsigned NOT NULL default '0',
  `terroristwon` smallint unsigned NOT NULL default '0',
  `terroristlost` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;

-- Moved from defaults.sql.
INSERT INTO `ps_config_events` (`id`, `gametype`, `modtype`, `eventname`, `alias`, `regex`, `idx`, `ignore`, `codefile`) 
    VALUES 
        (1,'halflife','','kill','','/^\"(.+(?:<[^>]*>))\" killed \"(.+(?:<[^>]*>))\" with \"([^\"]*)\"(.*)/',10,0,''),
        (2,'halflife','','attacked','','/^\"(.+(?:<[^>]*>))\" attacked \"(.+(?:<[^>]*>))\" with \"([^\"]+)\"(.*)/',20,1,''),
        (3,'halflife','','plrtrigger','','/^\"(.+(?:<[^>]*>))\" triggered \"([^\"]+)\"(.*)/',30,0,''),
        (4,'halflife','','round','','/^World triggered \"([^\"]+)\"(.*)/',40,0,''),
        (5,'halflife','','entered_game','','/^\"(.+(?:<[^>]*>))\" entered the game(.*)/',50,0,''),
        (6,'halflife','','joined_team','','/^\"(.+(?:<[^>]*>))\" joined team \"([^\"]+)\"/',60,0,''),
        (7,'halflife','','suicide','','/^\"(.+(?:<[^>]*>))\" committed suicide with \"([^\"]+)\"(.*)/',70,0,''),
        (8,'halflife','','changed_name','','/^\"(.+(?:<[^>]*>))\" changed name to \"([^\"]+)\"/',80,0,''),
        (9,'halflife','','connected','','/^\"(.+(?:<[^>]*>))\" connected, address \"([^\"]+)\"/',90,0,''),
        (10,'halflife','','connected_steamid','','/^\"(.+(?:<[^>]*>))\" (?:STEAM|VALVE) USERID (.+)/',100,0,''),
        (11,'halflife','','disconnected','','/^\"(.+(?:<[^>]*>))\" disconnected/',110,0,''),
        (12,'halflife','','chat','','/^\"(.+(?:<[^>]*>))\" say(_team)* \"(.*)\"?(.*)/',120,0,''),
        (13,'halflife','','rcon','','/^(Bad )?Rcon: \"rcon (-*\\d+) \"?(.*?)\"? (.+?)(?:\" from \"([^\"]+)\")?/',130,1,''),
        (14,'halflife','','cheated','','/^Secure: \"(.+(?:<[^>]*>))\" was detected cheating/',140,0,''),
        (15,'halflife','','ban','','/^(Addip|Ban(?:id)?): \"([^\"]+)\" was (?:kicked and )?(?:banned)(?: by IP)? \"([^\"]+)\" by \"([^\"]+)\"(.*)/',150,1,''),
        (16,'halflife','','unban','','/^Remove(id|ip): \"([^\"]+)\" was unbanned by \"(.+(?:<[^>]*>))\"(.*)/',160,1,''),
        (17,'halflife','','kick','','/^Kick: \"(.+(?:<[^>]*>))\" was kicked by \"(.+(?:<[^>]*>)?)\"(.*)/',170,0,''),
        (18,'halflife','','pingkick','','/^\"(.+(?:<[^>]*>))\" kicked due to high ping(.*)/',180,0,''),
        (19,'halflife','','ffkick','','/^\"(.+(?:<[^>]*>))\" has been auto kicked from the game for TKing/',190,0,''),
        (20,'halflife','','startedmap','','/^(Started|Loading) map \"([^\"]+)\"(.*)/',200,0,''),
        (21,'halflife','','logstartend','','/^Log file (started|closed)(.*)/',210,0,''),
        (22,'halflife','','ignored1','','/^[Ss]erver (?:cvars?|say|shutdown)/',220,1,''),
        (23,'halflife','','ignored2','','/^(?:\\]TSC\\[|Succeeded|FATAL|-|Loaded)/',230,1,''),
        (24,'halflife','','ignored3','','/^(?:Config|Swear|server_)/',240,1,''),
        (25,'halflife','','ignored4','','/^\"[^\"]+\" = \"/',250,1,''),
        (26,'halflife','cstrike','cs_teamscore','','/^Team \"([^\"]+)\" scored \"([^\"]+)\" with \"([^\"]+)\" players/',260,0,''),
        (27,'halflife','cstrike','teamtrigger','','/^Team \"([^\"]+)\" triggered \"([^\"]+)\"(.*)/',270,0,''),
        (28,'halflife','cstrike','cs_ignore1','','/^Counter-Strike Plugin/',280,1,''),
        (29,'halflife','cstrike','cs_ignore2','','/^Votemap/',290,1,''),
        (33,'halflife','','changed_role','','/^\"(.+(?:<[^>]*>))\" changed role to \"([^\"]+)\"/',330,0,''),
        (45,'halflife','','rcon2','','/^rcon from/',130,1,''),
        (48,'halflife','','spatial','','/^\\[KTRAJ\\] \"(.+(?:<[^>]*>))\" killed \"(.+(?:<[^>]*>))\" with \"([^\"]*)\"(.*)/',480,0,''),
        (49,'halflife','','plugin','','/^\\[[^\\]]+\\]/',490,1,''),
        (50,'halflife','','console','','/^(CONSOLE|PLAYER FILTER) :/',500,1,''),
        (100,'halflife','','ignored5','','/^Server name is \"([^"]+)\"/',1000,1,''),
        (101,'halflife','','ignored6','','/^Connection to Steam servers successful./',1010,1,''),
        (102,'halflife','','ignored7','','/^VAC secure mode is activated./',1020,1,''),
        (103,'halflife','','ignored8','','/^Assigned anonymous gameserver Steam ID \[(.:\\d:\\d+:\\d+)\]./',1030,1,''),
        (104,'halflife','','ignored9','','/^Public IP is ([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}|(\\d{1,3}\.){3}\\d{1,3}./',1040,1,'');

INSERT INTO `ps_config_plrbonuses` (`id`, `eventname`, `enactor`, `enactor_team`, `victim`, `victim_team`, `description`, `gametype`, `modtype`) 
    VALUES 
        (1,'planted_the_bomb',2,1,0,-1,'When a player plants the bomb','halflife','cstrike'),
        (2,'defused_the_bomb',2,0,-1,0,'A player defused the bomb successfully. Use the \'bomb_defused\' event for team bonses.','halflife','cstrike'),
        (3,'rescued_a_hostage',3,0,0,0,'When a player rescues a hostage','halflife','cstrike'),
        (7,'bomb_defused',0,2,0,-2,'TEAM event that fires when a round ends and the CT team defuses the bomb (use \'defused_the_bomb\' for enactor bonus)','halflife','cstrike'),
        (8,'bomb_runner',1,0,0,0,'Player spawned with and planted the bomb w/o dropping it','halflife','cstrike'),
        (10,'target_bombed',5,2,0,-2,'TEAM event that fires when the bomb explodes and the terrorists win','halflife','cstrike'),
        (12,'all_hostages_rescued',0,2,0,-2,'TEAM event that fires when all hostages on a CS map have been rescued (no enactor)','halflife','cstrike'),
        (13,'target_saved',0,5,0,-5,'TEAM event that fires when a round ends and the terrorists did not plant a bomb','halflife','cstrike'),
        (14,'hostages_not_rescued',0,2,0,-2,'TEAM event that fires when a round ends and the hostages are NOT rescued','halflife','cstrike'),
        (28,'killed_a_hostage',-3,0,0,0,'When a player kills a hostage','halflife','cstrike'),
        (29,'escaped_as_vip',10,0,0,0,'When a player escapes an \'es\' map as the VIP (use \'vip_escaped\' for team bonuses)','halflife','cstrike'),
        (30,'vip_escaped',0,5,0,-5,'TEAM event that fires when the VIP escapes the map (use escaped_as_vip for enactor bonus)','halflife','cstrike'),
        (31,'assassinated_the_vip',10,0,-5,0,'When a player kills the VIP (use \'vip_assassinated\' for team bonuses)','halflife','cstrike'),
        (32,'vip_assassinated',0,10,0,-10,'TEAM event that fires when the VIP was killed (use \'assassinated_the_vip\' for enactor bonus)','halflife','cstrike'),
        (33,'vip_not_escaped',0,5,0,-5,'TEAM event that fires when the VIP does not escape and terrorists win','halflife','cstrike'),
        (34,'ffkill',-10,0,0,0,'when a player kills a team mate','','');

INSERT INTO `ps_config_awards` (`id`, `enabled`, `idx`, `type`, `negative`, `class`, `name`, `groupname`, `phrase`, `expr`, `order`, `where`, `limit`, `format`, `gametype`, `modtype`, `rankedonly`, `description`) 
    VALUES 
        (4,1,10,'player',0,'','Highest Skill','','{$player.link} has the highest skill with {$award.value}','{$skill}','desc','',0,'%.02f',NULL,NULL,1,'Player with the highest skill'),
        (5,1,90,'player',0,'','Most Bombings','','{$player.link} has the most successful bombings ({$award.value} bombs)','{$bombexploded}','desc','',25,'commify','halflife','cstrike',1,'Players with the most successful bombed targets'),
        (6,1,20,'player',0,'','Most Kills','','{$player.link} has killed the most players ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Player with the most kills (any team)'),
        (7,1,110,'player',0,'','Most Hostages Rescued','','{$player.link} has rescued the most hostages ({$award.value})','{$rescuedhostages}','desc','',0,'commify','halflife','cstrike',1,'Players that risk life and limb to save hostages!'),
        (8,1,70,'player',0,'','Most Time Online','','{$player.link} has been online the longest ({$award.value})','{$onlinetime}','desc','',25,'compacttime',NULL,NULL,1,'Player with the most online time'),
        (9,1,190,'weaponclass',0,'','Most Kills with {$weapon.class} weapons','','{$player.link} has the most {$weapon.class} kills ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Most kills with {$weapon.class} type weapons (including: {$weapon.list}).'),
        (10,1,180,'weapon',0,'','Most Kills with {$weapon.name}','','{$player.link} has the most {$weapon.link} kills ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Most kills with a {$weapon.name}'),
        (11,1,80,'player',0,'','Demolitions Man','','{$player.link} has the best demolition percentage of {$award.value}','{$bombrunner} / {$bombexploded} * 100','desc','',25,'%0.02f%%','halflife','cstrike',1,'Players with the highest percentage of spawning with and planting the bomb and actually having it explode.'),
        (12,1,100,'player',0,'','Bomb Defusal Expert','','{$player.link} has the best defusal rating of {$award.value}','{$bombdefused} / {$bombdefuseattempts} * 100','desc','{$bombdefused} >= 5',25,'%0.02f%%','halflife','cstrike',1,'Player with the best bomb defuses percentage (must have at least 5 defuses to count)'),
        (13,1,30,'player',0,'','Most Bonus Points','','{$player.link} achieved the most bonus points ({$award.value})','{$totalbonus}','desc','',25,'commify',NULL,NULL,1,'Player that has achieved the most bonus points.'),
        (23,1,50,'player',1,'','Worst Teammate','','{$player.link} has killed the most teammates ({$award.value})','{$ffkills}','desc','',0,'commify',NULL,NULL,1,'Player with the most friendly fire kills (ie: Worst Teammate)'),
        (25,1,60,'player',1,'','Worst Team Kill Percentage','','{$player.link} has the highest team kill percentage ({$award.value})','{$ffkills} / {$kills} * 100','desc','',0,'%0.02f%%',NULL,NULL,1,'Player with the highest team kill percentage.'),
        (26,1,120,'player',1,'','Most Hostages Killed','','{$player.link} has killed the most hostages ({$award.value})','{$killedhostages}','desc','',0,'%s','halflife','cstrike',1,'Players that like to kill hostages instead of rescuing them.');

INSERT INTO `ps_config_overlays` (`id`, `gametype`, `modtype`, `map`, `minx`, `miny`, `maxx`, `maxy`, `width`, `height`, `flipv`, `fliph`, `rotate`) 
    VALUES 
        (29, 'halflife', 'cstrike', 'cs_assault', -4250, 3400, 7530, 7250, 485, 500, 1, 1, 0),
        (30, 'halflife', 'cstrike', 'cs_compound', 290, -2400, 5500, 3750, 373, 500, 1, 0, 0),
        (31, 'halflife', 'cstrike', 'cs_estate', -1135, -2175, 1311, 527, 647, 711, 1, 0, 0),
        (32, 'halflife', 'cstrike', 'cs_havana', -1520, -1220, 1700, 2300, 497, 500, 1, 0, 0),
        (33, 'halflife', 'cstrike', 'cs_italy', -1530, -2100, 1090, 2560, 284, 500, 1, 0, 0),
        (34, 'halflife', 'cstrike', 'cs_office', -1820, -2200, 2350, 1300, 598, 500, 1, 0, 0),
        (35, 'halflife', 'cstrike', 'cs_siege', -2813, -1391, 3911, 3895, 970, 765, 1, 0, 0),
        (36, 'halflife', 'cstrike', 'de_airstrip', -3239, -3279, 839, 2815, 640, 968, 1, 0, 0),
        (37, 'halflife', 'cstrike', 'de_aztec', -3130, -1770, 2980, 1500, 917, 500, 1, 0, 0),
        (38, 'halflife', 'cstrike', 'de_cbble', -3450, -2300, 1530, 2950, 475, 500, 1, 0, 0),
        (39, 'halflife', 'cstrike', 'de_chateau', -500, -1450, 3110, 2910, 417, 500, 1, 0, 0),
        (40, 'halflife', 'cstrike', 'de_dust', -2100, -1850, 2600, 3800, 409, 500, 1, 0, 0),
        (41, 'halflife', 'cstrike', 'de_dust2', -2240, -1080, 1800, 3320, 470, 500, 1, 0, 0),
        (42, 'halflife', 'cstrike', 'de_inferno', -2000, -800, 2800, 3640, 535, 500, 1, 0, 0),
        (43, 'halflife', 'cstrike', 'de_nuke', -3000, -2530, 3690, 960, 964, 500, 1, 0, 0),
        (44, 'halflife', 'cstrike', 'de_piranesi', -2900, -930, 2560, 2720, 759, 500, 1, 0, 0),
        (45, 'halflife', 'cstrike', 'de_prodigy', -220, -1640, 3350, 1050, 662, 500, 1, 0, 0),
        (46, 'halflife', 'cstrike', 'de_seasideresort', -1820, -2150, 2100, 4190, 308, 500, 1, 0, 0),
        (47, 'halflife', 'cstrike', 'de_survivor', -1903, -1263, 3455, 3055, 965, 764, 1, 0, 0),
        (48, 'halflife', 'cstrike', 'de_tides', -1750, -2000, 1300, 1280, 485, 500, 1, 0, 0),
        (49, 'halflife', 'cstrike', 'de_train', -2000, -1800, 2050, 1900, 560, 500, 1, 0, 0),
        (50, 'halflife', 'cstrike', 'dm_duel_v2', -770, -1209, 1614, 1232, 1002, 972, 1, 0, 0),
        (51, 'halflife', 'cstrike', 'fy_beachparty_v1', -288, -1008, 2192, 960, 1002, 972, 1, 0, 0),
        (52, 'halflife', 'cstrike', 'fy_iceworld', -752, -944, 752, 944, 1002, 972, 1, 0, 0),
        (53, 'halflife', 'cstrike', 'fy_paintball', 396, -1740, 1488, 778, 1002, 972, 1, 0, 0),
        (54, 'halflife', 'cstrike', 'fy_poolparty_v2', -264, -1966, 718, -205, 1002, 972, 1, 0, 0),
        (55, 'halflife', 'cstrike', 'fy_simpsons_h', -952, -461, 952, 469, 1002, 972, 1, 0, 0),
        (56, 'halflife', 'cstrike', 'fy_xbox', -1792, -672, 496, 672, 1002, 972, 1, 0, 0),
        (57, 'halflife', 'cstrike', 'tc_hydro', -5928, -3152, 6600, 2952, 1146, 564, 1, 0, 0);
        
INSERT INTO `ps_config` (`id`, `conftype`, `section`, `var`, `value`, `label`, `type`, `locked`, `verifycodes`, `options`, `help`) 
    VALUES 
        (1,'main',NULL,'meta_keywords','PsychoStats Game Server Player Statistics Counter-Strike Valve','Site HTML Meta Key Words','text',0,'','','These are the HTML meta key words for your PsychoStats.  They are used by search engines to provide search results.');
